version: "2"
services:
  api:
    build: .
    volumes:
      - .:/go/src/netpro/test-golang
    ports:
      - 8080:8080 # API server
      - 8888:8888 # beego diagnostics server
    depends_on:
      - postgres
    environment: # pass through environments for build / test purposes
      - CNX_ENV
      - CNX_CONSUMER=true
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: test-golang_dev
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    ports:
      - 1234:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

networks:
  default:
    driver: bridge
  services:
    driver: bridge